###
POST https://www.nutrition-service.com/load/user-info
Content-Type: application/json

{
  "openid": "test_openid_1235123"
}

###
GET https://www.nutrition-service.com/cuisine/cuisine-list?storeCode=100001&uuid=0
Content-Type: application/json