
### 启动测试
GET https://localhost/hello
Content-Type: application/x-www-form-urlencoded

### 添加饮食记录
GET https://localhost/user/save/cuisine-history?uuid=afc7fdc66d9a4fbf9211d787c1b42bbe&cuisineCode=1a219e3a71f34d8ebc2af9c3d2d6eef8

### 查询餐品详情
GET https://localhost/cuisine/query-details?cuisineCode=1a219e3a71f34d8ebc2af9c3d2d6eef8

### 查询门店列表
GET https://localhost/store/query/supported

### 加载用户信息
GET https://localhost/product/load/user-info?openid=ov5KQ4l0nO7L1k5d95_4xFvrIuxc

### 保存用户健康信息
POST https://localhost/user/save/user-info
Content-Type: application/json

{
  "uuid": "afc7fdc66d9a4fbf9211d787c1b42bbe",
  "gender": 1,
  "age": 28,
  "height": 181,
  "weight": 65,
  "profeChar": 1,
  "sportsHabits": 2,
  "goal": 2
}

### 查询已支持门店列表
GET https://localhost/store/query/supported

### 查询用户今日添加餐品列表
GET https://localhost/user/query/today-cuisine-history?uuid=afc7fdc66d9a4fbf9211d787c1b42bbe

### 查询用户信息
GET https://localhost/user/query/user-info?uuid=87391f78d143405b9de4ca9a8b35ef05

### 查询待催更功能列表
GET https://localhost/product/function-list?uuid=afc7fdc66d9a4fbf9211d787c1b42bbe

### 功能催更
GET https://localhost/product/push-function?uuid=afc7fdc66d9a4fbf9211d787c1b42bbe&functionCode=10001

### 用户提交建议
POST https://localhost/product/express-opinion
Content-Type: application/json

{
  "uuid":"87391f78d143405b9de4ca9a8b35ef05",
  "content": "咕咕咕咕",
  "contact": "咕咕"
}

### 用户推荐门店
POST https://localhost/product/recommend-store
Content-Type: application/json

{
  "uuid":"87391f78d143405b9de4ca9a8b35ef05",
  "storeName": "咕咕鸡鸡",
  "userAddress": "东直门外大街"
}